name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Job 1 !!"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: echo
        run: echo "Job 2 !!"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "Job 3 failed"
          exit 1
  job4:
    runs-on: ubuntu-latest
    needs: [job3]
    steps:
      - name: echo
        run: echo "Job 4 !!"
